Following [this tutorial](https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html)

In [1]:
import torch
torch.manual_seed(1)

In [3]:
vector_data = [1, 2, 3]
vector = torch.tensor(vector_data)
print(vector)

matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = torch.tensor(matrix_data)
print(matrix)

tensor_data = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
]
tensor = torch.tensor(tensor_data)
print(tensor)


tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])


In [6]:
print(vector[0])
print(vector[0].item())

print(matrix[0])
print(tensor[0])

tensor(1)
1
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[ 0.4100,  0.4085,  0.2579,  1.0950, -0.5065],
         [ 0.0998, -0.6540,  0.7317, -1.4567,  1.6089],
         [ 0.0938, -1.2597,  0.2546, -0.5020, -1.0412],
         [ 0.7323,  1.3075, -1.1628,  0.1196, -0.1631]],

        [[ 0.6614,  1.1899,  0.8165, -0.9135, -0.3538],
         [ 0.7639, -0.5890, -0.7636,  1.3352,  0.6043],
         [-0.1034, -0.1512,  1.2466,  0.5057,  0.9505],
         [ 1.2966,  0.8738, -0.5603,  1.2858,  0.8168]],

        [[-1.4648, -1.2629,  1.1220,  1.5663, -1.0371],
         [-1.0669, -0.2085, -0.2155,  0.2705,  0.5597],
         [-0.3184,  1.5117, -1.5208,  0.9196, -0.5484],
         [-0.3472, -0.7474, -0.9234,  0.5734, -0.1093]]])


In [9]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [10]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
# torch.cat([x_1, x_2])

tensor([[-6.9328e-01, -1.6676e-01, -9.9988e-01, -1.6476e+00,  8.0983e-01],
        [ 5.5424e-02,  1.1340e+00, -5.3264e-01,  6.5921e-01, -1.5964e+00],
        [-3.7687e-01, -3.1020e+00, -9.9467e-02, -7.2126e-01,  1.2708e+00],
        [-2.0225e-03, -1.0952e+00,  6.0165e-01,  6.9841e-01, -8.0052e-01],
        [ 1.5381e+00,  1.4673e+00,  1.5951e+00, -1.5279e+00,  1.0156e+00]])
tensor([[-0.2020, -1.2865,  0.8231,  0.6684,  1.1628, -0.3229,  1.8782, -0.5666],
        [-0.6101, -1.2960, -0.9434,  0.4016, -0.1153,  0.3170,  0.5629,  0.8662]])
