Following [this tutorial](https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html)

In [1]:
import torch
torch.manual_seed(1)

In [3]:
vector_data = [1, 2, 3]
vector = torch.tensor(vector_data)
print(vector)

matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = torch.tensor(matrix_data)
print(matrix)

tensor_data = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
]
tensor = torch.tensor(tensor_data)
print(tensor)


tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])


In [6]:
print(vector[0])
print(vector[0].item())

print(matrix[0])
print(tensor[0])

tensor(1)
1
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[ 0.4100,  0.4085,  0.2579,  1.0950, -0.5065],
         [ 0.0998, -0.6540,  0.7317, -1.4567,  1.6089],
         [ 0.0938, -1.2597,  0.2546, -0.5020, -1.0412],
         [ 0.7323,  1.3075, -1.1628,  0.1196, -0.1631]],

        [[ 0.6614,  1.1899,  0.8165, -0.9135, -0.3538],
         [ 0.7639, -0.5890, -0.7636,  1.3352,  0.6043],
         [-0.1034, -0.1512,  1.2466,  0.5057,  0.9505],
         [ 1.2966,  0.8738, -0.5603,  1.2858,  0.8168]],

        [[-1.4648, -1.2629,  1.1220,  1.5663, -1.0371],
         [-1.0669, -0.2085, -0.2155,  0.2705,  0.5597],
         [-0.3184,  1.5117, -1.5208,  0.9196, -0.5484],
         [-0.3472, -0.7474, -0.9234,  0.5734, -0.1093]]])


In [9]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [10]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
# torch.cat([x_1, x_2])

tensor([[-6.9328e-01, -1.6676e-01, -9.9988e-01, -1.6476e+00,  8.0983e-01],
        [ 5.5424e-02,  1.1340e+00, -5.3264e-01,  6.5921e-01, -1.5964e+00],
        [-3.7687e-01, -3.1020e+00, -9.9467e-02, -7.2126e-01,  1.2708e+00],
        [-2.0225e-03, -1.0952e+00,  6.0165e-01,  6.9841e-01, -8.0052e-01],
        [ 1.5381e+00,  1.4673e+00,  1.5951e+00, -1.5279e+00,  1.0156e+00]])
tensor([[-0.2020, -1.2865,  0.8231,  0.6684,  1.1628, -0.3229,  1.8782, -0.5666],
        [-0.6101, -1.2960, -0.9434,  0.4016, -0.1153,  0.3170,  0.5629,  0.8662]])


In [14]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))

tensor([[[-0.2278, -0.8676,  0.3398, -1.1494],
         [ 0.6522, -0.8726,  0.0353, -0.3365],
         [ 0.7225,  0.1526,  0.1450, -2.3442]],

        [[-0.4619, -0.3686,  0.3682,  0.4850],
         [ 0.1988,  0.5441, -0.3978, -1.9291],
         [ 0.9264,  0.9134, -0.7902, -0.5831]]])
tensor([[-0.2278, -0.8676,  0.3398, -1.1494,  0.6522, -0.8726,  0.0353, -0.3365,
          0.7225,  0.1526,  0.1450, -2.3442],
        [-0.4619, -0.3686,  0.3682,  0.4850,  0.1988,  0.5441, -0.3978, -1.9291,
          0.9264,  0.9134, -0.7902, -0.5831]])


In [12]:
print(x.view(2, -1))

tensor([[ 0.0127, -1.8734,  1.7997,  0.2824,  0.2151,  0.9385,  1.4657, -0.5565,
          2.4142,  1.0206, -0.4405, -1.7342],
        [-1.0257,  0.5213, -0.4531, -0.1260, -0.5882,  2.1189, -0.5422, -2.4593,
         -0.9502, -0.3095,  1.6633,  0.5051]])


In [17]:
# computation graphs and automatic differentiation

x = torch.tensor([1., 2., 3.], dtype=torch.float32, requires_grad=True)
y = torch.tensor([4., 5., 6.], dtype=torch.float32, requires_grad=True)
z = x + y

print(z)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [18]:
print(z.grad_fn)

In [19]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [20]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [21]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# By default, user created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

False False
None


In [22]:
# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.
x = x.requires_grad_()
y = y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

True


In [23]:
# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()

In [24]:

# ... does new_z have information to backprop to x and y?
# NO!
print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history

None


In [25]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
